name: CLI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: SSH Agent Action
        uses: truemark/ssh-agent-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
